// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhqSTdi4kipHc4DMAGz45nVfbSXeEWzk',
    appId: '1:111940326225:android:4f4e12042985c690027970',
    messagingSenderId: '111940326225',
    projectId: 'fruit-hub-8689f',
    storageBucket: 'fruit-hub-8689f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLm_rE6hEeM06uGLz5Jp6YoCVqhfFUdVI',
    appId: '1:111940326225:ios:ed36098a5beac3d0027970',
    messagingSenderId: '111940326225',
    projectId: 'fruit-hub-8689f',
    storageBucket: 'fruit-hub-8689f.firebasestorage.app',
    androidClientId: '111940326225-ht7vqa4a1c9u70gs4l749ikoqhrl3arj.apps.googleusercontent.com',
    iosClientId: '111940326225-l5siotd9a77g7b71iqnsg4ofjaoi77b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitesdashboard',
  );
}
