// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhqSTdi4kipHc4DMAGz45nVfbSXeEWzk',
    appId: '1:111940326225:android:4f4e12042985c690027970',
    messagingSenderId: '111940326225',
    projectId: 'fruit-hub-8689f',
    storageBucket: 'fruit-hub-8689f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLm_rE6hEeM06uGLz5Jp6YoCVqhfFUdVI',
    appId: '1:111940326225:ios:ed36098a5beac3d0027970',
    messagingSenderId: '111940326225',
    projectId: 'fruit-hub-8689f',
    storageBucket: 'fruit-hub-8689f.firebasestorage.app',
    androidClientId: '111940326225-2c3n5hfajldqnur8morsjfsrlhaudfsf.apps.googleusercontent.com',
    iosClientId: '111940326225-l5siotd9a77g7b71iqnsg4ofjaoi77b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitesdashboard',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB17blGB_XlOSZDlFdiObEhxdMlCZp7OG4',
    appId: '1:111940326225:web:bd37f4384388dadf027970',
    messagingSenderId: '111940326225',
    projectId: 'fruit-hub-8689f',
    authDomain: 'fruit-hub-8689f.firebaseapp.com',
    storageBucket: 'fruit-hub-8689f.firebasestorage.app',
    measurementId: 'G-9PC0JMH6V6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLm_rE6hEeM06uGLz5Jp6YoCVqhfFUdVI',
    appId: '1:111940326225:ios:ed36098a5beac3d0027970',
    messagingSenderId: '111940326225',
    projectId: 'fruit-hub-8689f',
    storageBucket: 'fruit-hub-8689f.firebasestorage.app',
    androidClientId: '111940326225-2c3n5hfajldqnur8morsjfsrlhaudfsf.apps.googleusercontent.com',
    iosClientId: '111940326225-l5siotd9a77g7b71iqnsg4ofjaoi77b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitesdashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB17blGB_XlOSZDlFdiObEhxdMlCZp7OG4',
    appId: '1:111940326225:web:c5165f47dc74d4bc027970',
    messagingSenderId: '111940326225',
    projectId: 'fruit-hub-8689f',
    authDomain: 'fruit-hub-8689f.firebaseapp.com',
    storageBucket: 'fruit-hub-8689f.firebasestorage.app',
    measurementId: 'G-15E8ZP98WR',
  );

}